name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - "master"
      
jobs:
  card-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm install

      - name: Puppeteer install
        run: PUPPETEER_PRODUCT=firefox npm i puppeteer

      - name: Pull from current branch
        run: git pull origin ${GITHUB_REF##*/}

      - name: Create dist folder if note exists
        run: mkdir -p dist

      - name: Open Graph social cards
        uses: Jasmin2895/open-graph-image@v1
        with:
          bold-text: "Support Chat"
          plain-text: "by twilio"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add images pulled from headless browser to folder
          commit_options: '--no-verify --signoff'
