name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - "master"
      
jobs:
  card-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Use Node.js 12.X
      - run: npm install
      - uses: actions/setup-node@v1
        name: use actions/setup-node
        with:
          node-version: "12.X"
        env:
          CI: true
      - name: Open Graph social cards
        uses: Jasmin2895/open-graph-image@v1
        with:
          bold-text: "Support Chat"
          plain-text: "by twilio"
