# This is a basic workflow to help you get started with Actions

name: Twilio actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: |
          npm install
          npm update

      # Runs a single command using the runners shell
      - name: Open Graph social cards
        uses: Jasmin2895/open-graph-image@v1.2
        with:
          bold-text: "Github CLI"
          plain-text: "1.0"
          theme: "dark"

      - name: Archive open graph image
        uses: actions/upload-artifact@v2
        with:
          name: open-graph-image
          path: og-image.now.sh.png

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        
      - name: Generate Image
        uses: BoyWithSilverWings/generate-og-image@1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          path: src/images/post-images/
