# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: delete node_module folder
        run: find . -name "node_modules" -type d -prune -exec rm -rf '{}' +
        
      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm install
        
      - name: Install webshot
        run: npm i webshot-node

      # Runs a single command using the runners shell
      - name: Open Graph social cards
        uses: Jasmin2895/open-graph-image@v1
        with:
          bold-text: "Open graph image"
          plain-text: "for social media platform"
